fix(config): circular dependency
remove `@Inject()` from configService injection
the error is caused by reflect-metadata/Reflect.js:541
```bash
Error: Token is undefined at index: 0. This often occurs due to circular dependencies.
Ensure there are no circular dependencies in your files or barrel files.
For more details, refer to https://trilon.io/blog/avoiding-circular-dependencies-in-nestjs.
```